# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-01 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongycosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='FriendShare',
            field=models.CharField(max_length=1000),
        ),
    ]
