# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongycosts', '0002_auto_20180401_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='FriendShare',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
