# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-18 19:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dongycosts', '0003_auto_20180403_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('ProfileId', models.AutoField(primary_key=True, serialize=False)),
                ('ProfileName', models.CharField(max_length=20)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='friends',
            name='ProfileID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='costs',
            name='FriendShare',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
