# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-18 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dongycosts', '0004_auto_20180518_1911'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together=set([('Username', 'FriendName', 'ProfileID')]),
        ),
    ]
